### ISSUE TITLE
Npm vs github

### ISSUE THREAD

**Issue by cosydney** [mohitk05/react-insta-stories#10]
It seems the github version of the source code is a bit different than the one on npm, version are differents and the github version the progress bar isn't progressing.. 

Is it the latest version on github? 

Thanks !

**Comment by cosydney** [comment]
I see the version on github is 1.3 and npm is 1.4.1, may be that's related?

**Comment by mohitk05** [comment]
Hey, not sure what version on github you are talking about. The code's package.json is the latest one, 1.4.1. https://github.com/mohitk05/react-insta-stories/blob/master/package.json

Are you talking about the release? I believe I need to update that one.
