### ISSUE TITLE
DefaultInterval works incorrectly with various refresh rates

### ISSUE THREAD

**Issue by 4e6yp** [mohitk05/react-insta-stories#101]
Due to the usage of `requestAnimationFrame` progress animation [expects](https://github.com/mohitk05/react-insta-stories/blob/v2.0.4/src/components/ProgressArray.tsx#L30) 60 frames per second. Hence on higher refresh rates monitors (e.g. 120hz) duration of the story component is 2 times faster than expected by the `DefaultInterval` value. 
Also, `requestAnimationFrame` is affected by hardware acceleration. 

IMO, it's better to split animation and slide progression into separate logic.

**Comment by mohitk05** [comment]
Please upgrade to v2.5.8 or up!
