### ISSUE TITLE
document is not defined

### ISSUE THREAD

**Issue by parshantdhall** [mohitk05/react-insta-stories#102]
I was trying to import this package in my next js app but its showing the 'document not defined error'.

**Comment by solkpolk** [comment]
`const ReactStories = dynamic( 
  (props) => import('react-insta-stories'),
  {ssr: false},
)`

`<ReactStories
              stories={stories} 
              width={300}
              height={600}
              loop        
            />`

I think its because the package only works on the browser and Next.js comes with server-side magic

**Comment by parshantdhall** [comment]
Tha

> `const ReactStories = dynamic( (props) => import('react-insta-stories'), {ssr: false}, )`
> 
> `<ReactStories stories={stories} width={300} height={600} loop />`
> 
> I think its because the package only works on the browser and Next.js comes with server-side magic

Thanks man it finally worked
