### ISSUE TITLE
Passing an object instead of url

### ISSUE THREAD

**Issue by AhmetCetinn** [mohitk05/react-insta-stories#11]
Thanks for useable package. Story type can be improved. If story props pass as not only url but also object, it will be awesome. (For example: **lottie file** )

**Comment by mohitk05** [comment]
Sure, this is in todo list. Will take this up soon.

**Comment by mohitk05** [comment]
@AhmetCetinn Checkout v2, released today! You can render your own JSX inside of a story now.
