### ISSUE TITLE
I want to help contribute to renderer but need help starting

### ISSUE THREAD

**Issue by ajmalafif** [mohitk05/react-insta-stories#111]
Hi, 

I am more of a frontend designer so I want to help with renderer but I don‘t know where to start. It will be great if there‘s like a starter or an isolated files/configs that I then can contribute to. Thank you!

**Comment by mohitk05** [comment]
Hello @ajmalafif , thanks for willing to contribute. I haven't yet written a specific document for creating a renderer, but you can refer to the image renderer that is used inside the module to create your own.
https://github.com/mohitk05/react-insta-stories/blob/master/src/renderers/Image.tsx

Here is some documentation for renderers and how they work:
https://github.com/mohitk05/react-insta-stories#renderers

I'll write a dedicated article for this, until then you can use the above resources. Let me know if you need help there.

**Comment by ajmalafif** [comment]
hey @mohitk05 thank you for directing me towards the right file I‘ll take a look and ask any question I might have!
