### ISSUE TITLE
Add custom styles to story, i.e main story wrapper

### ISSUE THREAD

**Issue by Imran31** [mohitk05/react-insta-stories#118]
As of now we can only add style to images of the story but not the story container. I wanted to add a border-radius so that the story resembles Instagram a bit more, as of now we only have props for width and height. 

Example:

<img width="626" alt="Screenshot 2021-05-11 at 1 59 55 AM" src="https://user-images.githubusercontent.com/11473000/117720949-ebbf7480-b1fc-11eb-9cce-55db4dd0697e.png">

**Comment by JamesBotterill** [comment]
I'm looking to do the same things, right now it's  seems like a pretty hacky proposition.

**Comment by JamesBotterill** [comment]
Not sure a prop is helpful for this, a more flexible solution is to expose the divs needed to do this via a class and then add the extra styling using CSS.

**Comment by mohitk05** [comment]
Adding a prop `storyContainerStyles` to pass in styles for the container. @JamesBotterill what would be the advantage of exposing a class? You might not be able to override certain inline styles applied to the container.

**Comment by mohitk05** [comment]
Please update to v2.2.0.
