### ISSUE TITLE
No voice in video

### ISSUE THREAD

**Issue by dklymenko-blackbird** [mohitk05/react-insta-stories#121]
There is no sound if the stories consist only of video, but if you add one story with a picture at the beginning of the story, then the sound appears

**Comment by mohitk05** [comment]
@dklymenko-blackbird this is a deliberate thing. Most browsers do not allow auto-playing videos without any user interaction. So you would have to let the user interact with some element first before loading the stories if you wish to have sound in the first video.

Even with the image, if you do not tap to go to the next slide, the video won't have sound. I'd suggest adding some button to start the stories if you need the sound.

**Comment by dklymenko-blackbird** [comment]
But I jumped between videos many times and it is muted anyway. And one more thing, in this case i can't find some property for prevent stories auto play. Could you pls help?

**Comment by dklymenko-blackbird** [comment]
I added Unmute button for unmute videos

**Comment by marotzke** [comment]
@dklymenko-blackbird how did you manage to unmute the video inside the library?
