### ISSUE TITLE
Unable to preventDefault inside passive event listener invocation.

### ISSUE THREAD

**Issue by webdevsyd** [mohitk05/react-insta-stories#127]
I am getting this error on my current project whenever I tap the left and right part of the screen:
Error: Unable to preventDefault inside passive event listener invocation.

Also when I need to tap the screen to move the active story to the next story, it's not auto-playing.

I am using the following version:

React: 17.0.2
React dom: 17.0.2

Code:
```
import React from 'react';
import Stories from 'react-insta-stories';

const stories = [
  {
    url: 'https://picsum.photos/1080/1920',
  },
  {
    url: 'https://picsum.photos/1080/1920',
  },
  {
    url: 'https://picsum.photos/1080/1920',
  },
  {
    url: 'https://picsum.photos/1080/1920',
  },
  {
    url: 'https://picsum.photos/1080/1920',
  },
];

const StorySlider = () => <Stories defaultInterval={1000} stories={stories} />;

export default StorySlider;
```

**Comment by augustomatosdev** [comment]
Same here

**Comment by mohitk05** [comment]
This looks to be due to the delegation of event object happening inside `onMouseUp` and `onTouchEnd` listeners. Fixing this is v2.2.3.

**Comment by mohitk05** [comment]
Closing this, please reopen if the issue still persists in `2.2.3`.

**Comment by arpitprod** [comment]
I'm facing same. My version is 2.2.5

**Comment by shotaKvitsashvili** [comment]
> I'm facing same. My version is 2.2.5

same. problem is not fixed to me too

**Comment by mohitk05** [comment]
@arpitprod @shotaKvitsashvili Can you let me know which browser are you using, and maybe the exact error stack trace?

**Comment by shotaKvitsashvili** [comment]
> @arpitprod @shotaKvitsashvili Can you let me know which browser are you using, and maybe the exact error stack trace?
> 
> I have created a sample codesandbox with v2.3.0, but could not reproduce this. https://codesandbox.io/s/affectionate-rain-pownm?file=/src/App.js

I copy/pasted your sandbox and It gave me the same error (I'm using Chrome).
I noticed one thing: When I click it doesn't give me errors, but when I use Toggle Device Toolbar, it does.
Maybe because, instead of click, tap/touch listener gets triggered? And it causes error
