### ISSUE TITLE
this project not run in local device 

### ISSUE THREAD

**Issue by ahmedzaki72** [mohitk05/react-insta-stories#13]
when  git clone this app and do npm install  and use npm start give me this message and not run 

rollup v0.64.1
bundles src/index.js → dist/index.js, dist/index.es.js...
created dist/index.js, dist/index.es.js in 709ms

[2019-04-22 17:15:32] waiting for changes..

please how to solve this problem

**Comment by mohitk05** [comment]
Hey, that is the correct behaviour. `git clone` clones the package repository. So `npm start` in the root folder starts the rollup server. For running the example, cd into the ghpage folder and start the app:
`cd ghpage && npm install && npm start`.
