### ISSUE TITLE
Build issue due to "React" case sensitive

### ISSUE THREAD

**Issue by michel-p** [mohitk05/react-insta-stories#136]
Hello,

I am trying to use this library in my project but I get this error when launching the build
`
ModuleNotFoundError: Module not found: Error: Can't resolve 'React' in '../node_modules/react-insta-stories/dist'
...
resolve 'React' in '../node_modules/react-insta-stories/dist'
  Parsed request is a module
  using description file: ../node_modules/react-insta-stories/package.json (relative path: ./dist)
`
the bug is fixed when I go in node_modules/react-insta-stories/dist/index.js and change define("Stories",["React"],t)  in define("Stories",["react"],t)

I was wondering if this could be related to a mistake done here https://github.com/mohitk05/react-insta-stories/blob/master/webpack.config.js#L59-L60 (amd: 'React') ?

Thank you very much for your help

**Comment by mohitk05** [comment]
Hey, `react` and `react-dom` are peer dependencies for this package. You might have to install them manually if you haven't. Let me know if the issue still persists - I tried with v2.2.0 locally and I could build the app successfully.

**Comment by michel-p** [comment]
I already have these dependencies on my main project. What I had to do is to add a webpack configuration. If someone faces the same problem :
`module.exports = (env, paths) => ({
  alias: {
    React: `${paths.appNodeModules}/react`,`
