### ISSUE TITLE
Invariant Violation: View config getter callback for component `div` must be a function

### ISSUE THREAD

**Issue by subhampanja** [mohitk05/react-insta-stories#148]
Always showing error.. 
Invariant Violation: View config getter callback for component `div` must be a function

I tried all type of stories as per instruction. but showing error

**Comment by mohitk05** [comment]
Hey, can you post your code here? Let me know how you are using the component.

**Comment by subhampanja** [comment]
> Hey, can you post your code here? Let me know how you are using the component.

Here is the photo

//code photo
https://i.ibb.co/6JfPb7Q/code.png

//error photo
https://i.ibb.co/xFfP4br/errormain.png

Please help me. I already posted the issue on discord also

**Comment by mohitk05** [comment]
Oh, I see you are trying to use this library in React Native, but this only supports web currently.

**Comment by subhampanja** [comment]
> Oh, I see you are trying to use this library in React Native, but this only supports web currently.

Thank you. actually your package ranking on google for keyword "React Native Stories"

**Comment by subhampanja** [comment]
thanks for the infromation

**Comment by AnatuGreen** [comment]
I just spent 1 hour trying to fix this error in react native. I did not know it was for only react. LMAO😂😂😂.
But this is such a nice stuff that should be available for react native. Please extend it to us. Thank you
