### ISSUE TITLE
currentId does not reset with change in stories Props

### ISSUE THREAD

**Issue by MSalmanTariq** [mohitk05/react-insta-stories#15]
Updating the stories props for rendering different stories from different person can't reset the counter for new props that is a new array of stories pass to a story component. Which cause new stories to start from the counter where we left our previous stories.
For eg. I have a list of persons who uploaded there stories 
Mr X uploaded 5 pictures 
Mr Y uploaded 4 pictures
I saw 3 pictures of Mr X from Start and switch to Mr Y stories , So Mr Y stories does not start with the position 1 , it starts from picture 4 because I saw 3 pictures of Mr X and counter does not reset with change in props

**Comment by mohitk05** [comment]
@MSalmanTariq thanks for reporting this bug. Would you be able to take this up and submit a PR? Or else I'll start this one in a few days.

**Comment by mohitk05** [comment]
@MSalmanTariq This is one of the fixes included in version 2, which is currently in a PR, will soon be published.

**Comment by mohitk05** [comment]
@MSalmanTariq Please check v2, which is live now. You can use the prop `currentId` to control the story to be shown, also the issue you had mentioned is now fixed.
