### ISSUE TITLE
TypeError: Cannot read property 'content' of undefined

### ISSUE THREAD

**Issue by enkhee** [mohitk05/react-insta-stories#155]
Nextjs Project 
yarn build  error 
nextjs 11
![image](https://user-images.githubusercontent.com/1201860/127678080-455f4548-e260-43bd-acb7-d91277e46f81.png)

**Comment by enkhee** [comment]
Fixed

**Comment by DevSebas-Code** [comment]
Hey @enkhee , i'm having the same issue, could you tell how you fixed it, please.

Greetings.
