### ISSUE TITLE
center images

### ISSUE THREAD

**Issue by Ramsteven** [mohitk05/react-insta-stories#167]
hi, I am working on an application web, but a couldn't center images, I am try with the documentation but, i didn't that, can help me? this is the current result, but I wanna center the image with the container.
![ssss](https://user-images.githubusercontent.com/23351805/136272696-b318b290-8577-4645-bcdb-336247b61256.PNG)
this is a component that I am using, I got Miu for the modal popup.

        `<div className={s.container}>
            <Dialog
            open={open}
            onClose={handleClose}
            fullWidth
            maxWidth="lg"
          
            aria-labelledby="alert-dialog-title"
            aria-describedby="alert-dialog-description"
            >
            
                        <Stories
                          stories={arrayStories}
                          defaultInterval={900}
                          width={"100%"}
                          height={"800px"}
                          loop={true}
                          
                        />
     
            </Dialog>
        </div>  `

**Comment by mohitk05** [comment]
You can find the solution is #177.
