### ISSUE TITLE
Content not getting displayed for type:'video'

### ISSUE THREAD

**Issue by kaleem68** [mohitk05/react-insta-stories#169]
the content is not display when video type is 'video' when type is not video the content is displayed fine
urlLink is video if type:'video' otherwise URL of photo, please help

here content  is not displayed
let mystories = [ {

                url: urlLink,
                type: 'video',
                header: {
                    heading: 'Mohit Karekar',
                    subheading: 'Posted 30m ago',
                    profileImage: 'https://picsum.photos/100/100',
                },
                seeMore: ({ close }) => {
                    return <div onClick={close}>Hello, click to close this.</div>;
                },

                content: (props) => (
                    <div style={{ background: 'pink', padding: 20 }}>
                        <h1 style={{ marginTop: '100%', marginBottom: 0 }}>🌝</h1>
                        <h1 style={{ marginTop: 5 }}>A custom title can go here.</h1>
                    </div>
                )
            }]

**Comment by mohitk05** [comment]
Hey @kaleem68, I think your understanding of how `content` works is incorrect. It only works standalone. So if your type is video, it will treat the story as a video. It will not overlay the content on top of the video, if that is what you were expecting.
For such a feature, you can decide to build a custom renderer which does this. Please refer to the docs for renderers, you should be able to do this with the existing APIs.
