### ISSUE TITLE
Center video\Image object

### ISSUE THREAD

**Issue by orizvida** [mohitk05/react-insta-stories#177]
Hey,
there is no way to center an image or video, align-items does not work, there should be an option to give the parent element justifyContent:"center"

**Comment by mohitk05** [comment]
@orizvida you can use the `content` property instead for the story. Following is an example:

```jsx
{
    content: () => <div style={{display: 'flex', flex: 1, justifyContent: 'center'}}>
                       <img style={{ display: 'block' }} src="https://via.placeholder.com/300" />
                   </div>
}
```
