### ISSUE TITLE
can't install bcz of peer-dependency

### ISSUE THREAD

**Issue by deadcoder0904** [mohitk05/react-insta-stories#192]
this line in `package.json` under `peerDependency` is the culprit.

> "react": "^16.8.2"

can you release a new version without any `peerDependency` as i don't think it's required? i'm on `^17.0.2` currently but it will probably through error when new react versions are released without the `peerDependency` being updated 👍

currently, solving it with `--legacy-peer-deps` flag :)

**Comment by AeShevch** [comment]
The same error, please update the dependencies.

```
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^16.8.2" from react-insta-stories@2.3.0
npm ERR! node_modules/react-insta-stories
npm ERR!   react-insta-stories@"^2.3.0" from the root project
npm ERR! 
npm ERR! Conflicting peer dependency: react@16.14.0
npm ERR! node_modules/react
npm ERR!   peer react@"^16.8.2" from react-insta-stories@2.3.0
npm ERR!   node_modules/react-insta-stories
npm ERR!     react-insta-stories@"^2.3.0" from the root project

```

**Comment by mohitk05** [comment]
Hello, I've updated the peerDependencies, please update to version `2.4.1`.
