### ISSUE TITLE
Only first story plays, then it gets stuck

### ISSUE THREAD

**Issue by SaadBazaz** [mohitk05/react-insta-stories#214]
Hey there,
Thanks for the library. Looking forward for it to work as it could solve many headaches.

I use:
```
    "next": "12.1.6",
    "react": "18.1.0",
```

I installed the library with force via npm: ```npm i react-insta-stories --force```

I use the following code to display the Stories:
```
import React, { Component } from 'react';

import dynamic from "next/dynamic";

// import Stories from 'react-insta-stories';
const ReactStories = dynamic( (props) => import('react-insta-stories'), {ssr: false}, )


const App = () => {

    const stories = [
        'https://cdn.vox-cdn.com/thumbor/u7eoI5OEXTO2lGPzRcOalu9_oDE=/0x0:2913x4377/1200x675/filters:focal(1253x693:1719x1159)/cdn.vox-cdn.com/uploads/chorus_image/image/60759779/860576078.jpg.1533693436.jpg',
        'https://techcrunch.com/wp-content/uploads/2016/08/instagram-ceo-kevin-systrom.jpg',
    ];

    return (
        <div style={{
            height: "100vh",
            width: "100vw",
            display: "flex",
            flexDirection: "column",
            alignItems: "center",
            justifyContent: "center"
        }}>
            <ReactStories
                stories={stories}
                defaultInterval={1500}
                width={350}
                height={"69vh"}
                loop
            />
        </div>
    );
};

export default App;
```

As you can see from the above code, I used the simple url string method to load the data.

It loads correctly but only shows the **first story**, after which it gets stuck.

Screengrab is attached.

https://user-images.githubusercontent.com/51885228/173635652-5f88b759-c36a-4c45-889e-7a9871b4c704.mov

**Comment by mohitk05** [comment]
Hey @SaadBazaz , I tried replicating this issue but could not. Here's a codesandbox link: https://codesandbox.io/s/distracted-hertz-5j50ii?file=/pages/index.js

**Comment by SaadBazaz** [comment]
That's strange... It seems to work in the CodePen example. I'll have a look at any globals which might be bothering my setup.

**Comment by leonardolessa** [comment]
Locally I'm having the same behavior with the following packages:

"next": "12.1.6",
"react": "18.2.0",
"react-dom": "18.2.0",
"react-insta-stories": "^2.4.1",

including the click on the left side it seems that the progress bar increases a little bit

**Comment by SaadBazaz** [comment]
@leonardolessa Same problem. It seems like something is wrong when updating state for the next() function. To fix it, I override the next function which is provided by this package. Here's an example:

```
const [ currentId, setCurrentId ] = useState(0);

...

            <Stories
                currentIndex={currentId}
                loop
                keyboardNavigation
                defaultInterval={3000}
                stories={stories2}
                onStoryEnd={(s, st) => {
                    console.log('story ended', s, st);
                    setCurrentId(currentId => currentId + 1);
                }}
                onAllStoriesEnd={(s, st) => {
                    console.log('all stories ended', s, st);
                    setCurrentId(currentId => 0);
                }}
                onStoryStart={(s, st) => {
                    console.log('story started', s, st);
                    setCurrentId(currentId => (currentId + 1) - 1);
                }}
                
            />
```

**Comment by SaadBazaz** [comment]
Could the latest version of React be causing the issue? https://betterprogramming.pub/react-v18-why-useeffect-suddenly-go-crazy-db1b42eb2730

According to the above article, React 18 does double-renders to force developers to improve coding practices.

Maybe we can try reducing the React version and seeing if the issue reproduces?

**Comment by leonardolessa** [comment]
> Could the latest version of React be causing the issue? https://betterprogramming.pub/react-v18-why-useeffect-suddenly-go-crazy-db1b42eb2730
> 
> According to the above article, React 18 does double-renders to force developers to improve coding practices.
> 
> Maybe we can try reducing the React version and seeing if the issue reproduces?

Thanks about the article. @SaadBazaz 
I understand why the core team did that but it seems counterintuitive if you're not aware about this behavior.
Turning off react strict mode on nuxt.config fixes the issue, so I guess you're absolutely right.
Thanks a lot.

**Comment by SaadBazaz** [comment]
@leonardolessa ...... That fixed MY issue too 🤣 
Turned it off in ```next.config.js``` and almost everything is working now. Thank you so much.

However, the question still remains... why is it being triggered and what can we do to this lib to improve it?

**Comment by mohitk05** [comment]
Hello! Thanks for the discussion people! You are welcome to raise PRs and improve the package 💯

**Comment by sgm17** [comment]
I had the same problem as the op and I'm sure someone will help. In development and because of the strict mode in the index.tsx file, certain elements are rendered twice. That causes it to not work properly. After a while I was able to fix it.

```javascript

/* root.render(
  <React.StrictMode>
    <Provider store={store}>
      <App />
    </Provider>
  </React.StrictMode>
); */

root.render(
  <Provider store={store}>
    <App />
  </Provider>
);
```

**Comment by hecforga** [comment]
I found a workaround to this problem without disabling React strict mode (proposed by @leonardolessa and which didn't work for me), and working also on touchscreens (in which I experienced problems with the `onStoryEnd`, `onAllStoriesEnd` and `onStoryStart` callbacks proposed by @SaadBazaz). It those solutions work for you, perfect. If not, try this one.

Code getting stuck:

```
<Stories
  stories={suggestions.map((s) => ({
    content: ({ action }) => {
      return (
        <div className="story-container">
          <ImageAbsoluteContainer>
            <ImageContainer>
              <Image
                alt={s.picturePath}
                layout="fill"
                objectFit="cover"
                objectPosition={s.objectPosition}
                src={`/images/${s.picturePath}`}
              />
            </ImageContainer>
          </ImageAbsoluteContainer>
        </div>
      );
    },
  }))}
  defaultInterval={5000}
  width="inherit"
  height="inherit"
  loop
/>
```

Code with workound (check the `action('play')` call inside `useEffect`):

```
<Stories
  stories={suggestions.map((s) => ({
    content: ({ action }) => {
      useEffect(() => {
        setTimeout(() => action('play'));
      }, []);
      return (
        <div className="story-container">
          <ImageAbsoluteContainer>
            <ImageContainer>
              <Image
                alt={s.picturePath}
                layout="fill"
                objectFit="cover"
                objectPosition={s.objectPosition}
                src={`/images/${s.picturePath}`}
              />
            </ImageContainer>
          </ImageAbsoluteContainer>
        </div>
      );
    },
  }))}
  defaultInterval={5000}
  width="inherit"
  height="inherit"
  loop
/>
```

**Comment by helians11** [comment]
I have react 18.20, and react-insta-stories as 2.6.2 with ReactStrictMode disabled, but still facing the above issues. Tried all the solutions but still on click of previous it is taking me to next story.

**Comment by svmurvi** [comment]
> I found a workaround to this problem without disabling React strict mode (proposed by @leonardolessa and which didn't work for me), and working also on touchscreens (in which I experienced problems with the `onStoryEnd`, `onAllStoriesEnd` and `onStoryStart` callbacks proposed by @SaadBazaz). It those solutions work for you, perfect. If not, try this one.
> 
> Code getting stuck:
> 
> ```
> <Stories
>   stories={suggestions.map((s) => ({
>     content: ({ action }) => {
>       return (
>         <div className="story-container">
>           <ImageAbsoluteContainer>
>             <ImageContainer>
>               <Image
>                 alt={s.picturePath}
>                 layout="fill"
>                 objectFit="cover"
>                 objectPosition={s.objectPosition}
>                 src={`/images/${s.picturePath}`}
>               />
>             </ImageContainer>
>           </ImageAbsoluteContainer>
>         </div>
>       );
>     },
>   }))}
>   defaultInterval={5000}
>   width="inherit"
>   height="inherit"
>   loop
> />
> ```
> 
> Code with workound (check the `action('play')` call inside `useEffect`):
> 
> ```
> <Stories
>   stories={suggestions.map((s) => ({
>     content: ({ action }) => {
>       useEffect(() => {
>         setTimeout(() => action('play'));
>       }, []);
>       return (
>         <div className="story-container">
>           <ImageAbsoluteContainer>
>             <ImageContainer>
>               <Image
>                 alt={s.picturePath}
>                 layout="fill"
>                 objectFit="cover"
>                 objectPosition={s.objectPosition}
>                 src={`/images/${s.picturePath}`}
>               />
>             </ImageContainer>
>           </ImageAbsoluteContainer>
>         </div>
>       );
>     },
>   }))}
>   defaultInterval={5000}
>   width="inherit"
>   height="inherit"
>   loop
> />
> ```

Have the same issue
I needed to add buttons with the functionality of switching story slides, there were no problems with them, my solution was

```javascript
const [storySlideIndex, setStorySlideIndex] = useState(0);

  const slidePrevStorySlide = () => {
    setStorySlideIndex(prev => prev - 1);
  };

  const slideNextStorySlide = () => {
    setStorySlideIndex(prev => prev + 1);
  };
  ``` 
  
and then I passed the ```currentIndex``` prop into my stories component.
And in order to synchronize changes in the current index with switching both by clicking inside the story and by clicking my buttons, I needed to use the ```onStoryStart``` ```onStoryEnd``` props, but when using them, the next slide of the story began immediately paused when played without user intervention.
This solution to launch history on the mount component helped me a lot

I want to say thank you for this package of stories, the package is wonderful and I’m glad that there are no third-party dependencies.
Request to the owner of the package, or to those who have time to create a PR and solve the problem - It would be nice to add a custom hook for managing the state of slides, which would provide callbacks for managing slides, the slide index and perhaps something else, so that users who have a similar task to mine could do this much easier
