### ISSUE TITLE
storyContainerStyles does not truly override the story container's styles

### ISSUE THREAD

**Issue by SaadBazaz** [mohitk05/react-insta-stories#215]
When I add the following:
```
                    storyContainerStyles={{ 
                        borderRadius: 8, 
                        overflow: 'visible', 
                        background: 'transparent',
                    }}
```

The ```background``` property does not work. Upon inspection in the Browser's Inspect Element, I find that another background is being added anyway to the styles:
```
<div style="border-radius:8px;overflow:visible;background:#111;display:flex;flex-direction:column;position:relative;width:360px;height:69vh">
...
</div>
```

i.e. ```background:#111``` is being set, probably in the internal code somewhere.

It seems like the Stories code prefers the default style fields over our overriden ones. Which should be the other way around, imo. Whatever the Developer prefers should be the first and foremost option.

**Comment by abhishekashyap** [comment]
Were you able to resolve this @SaadBazaz ?

**Comment by SaadBazaz** [comment]
I merged a PR for this issue. Worked after that.
