### ISSUE TITLE
only the first image will load after it will struck 

### ISSUE THREAD

**Issue by brnandhu001** [mohitk05/react-insta-stories#229]

**Comment by chaitan94** [comment]
This is a duplicate of #214. As mentioned in [a comment](https://github.com/mohitk05/react-insta-stories/issues/214#issuecomment-1159517781) in the other issue, turning off react strict mode is a workaround for this issue as of now.

**Comment by exotexot** [comment]
Removing Strict Mode didn't solve the issue for me...

**Comment by mohitk05** [comment]
Hello, please update to v2.5.0 which includes a fix for this issue.
