### ISSUE TITLE
Story(Video) duration less than expecting

### ISSUE THREAD

**Issue by AndriyRubanskui** [mohitk05/react-insta-stories#235]
The duration of one story is depend on monitor hz. Story are shorter with 120hz

**Comment by qanelph** [comment]
@AndriyRubanskui @mohitk05 any ideas?
requestAnimationFrame(checkRefreshRate) doesn't help;

**Comment by mohitk05** [comment]
Hey, this should be fixed in the latest version.

**Comment by qanelph** [comment]
## fixed in #271

@mohitk05 yep, it works like a charm now! 
checked it using 30, 60 and 120hz;

thank you so much! <3

**Comment by mohitk05** [comment]
Thanks to the amazing contributor who fixed this 🙌
