### ISSUE TITLE
story autoplay not working or the intervel not working

### ISSUE THREAD

**Issue by nisamozr** [mohitk05/react-insta-stories#239]
only when click on story its going to next story .else its  stay on the same story.

 <Stories
                        stories={stories}
                        keyboardNavigation={true}
                        width="100%"
                        height="100vh"
                        defaultInterval={8000}
                        loop={false}

                    />

**Comment by agustinaj** [comment]
Version ? code? can you fix this ?

**Comment by mohitk05** [comment]
Hello, please update to v2.5.0 which includes a fix for this issue.
