### ISSUE TITLE
Scrolling on Story

### ISSUE THREAD

**Issue by rulfo71** [mohitk05/react-insta-stories#323]
Hi! 
Is it possible to add vertical scrolling in a Story? 

I tried on the `storyContainerStyles`, `storyStyles` and didn't work
also tried on my content object like this: 

```
{
      content: Digest,
      styles: {
        overflow: "scroll",
        width: "auto",
        maxWidth: "100%",
        maxHeight: "100%",
        margin: "auto",
      },
    },
```

when looking through the console there seems to be an `overflow:hidden` i'm not being able to remove

thanks in advance!

**Comment by joeyhotz** [comment]
did you manage to solve this?

**Comment by rulfo71** [comment]
hi @joeyhotz not really, what i end up doing was adding a see more and i could add scrolling there, i think that's the way to do it
