### ISSUE TITLE
Completion callback

### ISSUE THREAD

**Issue by ryanadamwilson** [mohitk05/react-insta-stories#34]
Can you add a callback function that is fired at the completion of all stories?

When are you planning on releasing V2? I see your open PR, just curious.

**Comment by mohitk05** [comment]
Yes, noted. V2 will mostly be out by end of October.

**Comment by mohitk05** [comment]
@ryanadamwilson Please check the new version, read `New props` under the Props section, there are three event callbacks available now 🌟 I believe the one you are looking for is `onAllStoriesEnd `.

**Comment by rahulbansal16** [comment]
@mohitk05 There is a memory leak in the onAllStoriesEnd method. It is getting called on the old Story Component even if the new component renders.

**Comment by stanshivam** [comment]
> @mohitk05 There is a memory leak in the onAllStoriesEnd method. It is getting called on the old Story Component even if the new component renders.

Same issue. Got blocked due to this. Any work around?
