### ISSUE TITLE
How to run the example locally

### ISSUE THREAD

**Issue by khawerrind** [mohitk05/react-insta-stories#5]
Thank you for the great plugin. It will be nice to have some description in the readme to run this project locally. I am having trouble starting it up locally. I am having the following error while running `npm run deploy`

```
npm ERR! path /Users/khawer/Projects/react-insta-stories/example/node_modules/.staging/react-insta-stories-4f928e7d/node_modules/@babel/code-frame
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall rename
npm ERR! enoent ENOENT: no such file or directory, rename '/Users/khawer/Projects/react-insta-stories/example/node_modules/.staging/react-insta-stories-4f928e7d/node_modules/@babel/code-frame' -> '/Users/khawer/Projects/react-insta-stories/example/node_modules/.staging/@babel/code-frame-1ad58ac3'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent
```

**Node Version:** 11.3.0
**NPM Version:** 6.4.1

**Comment by khawerrind** [comment]
I had to remove `package-lock.json` both from example folder as well as from main directory. Now it is working fine. Once again thank you for the great plugin.

**Comment by mohitk05** [comment]
Hey, glad you liked the module. I'll write a part in the readme for running the example locally!
