### ISSUE TITLE
next() and previous() in version 2

### ISSUE THREAD

**Issue by minhle140198** [mohitk05/react-insta-stories#55]
I want to create 2 button - back and next to control stories, but I don't know how to use the next() and previous() function in version 2. Please help me!

**Comment by mohitk05** [comment]
Hey, you can check out the new props added in v2 https://github.com/mohitk05/react-insta-stories#props. To change the current story, you can create a function of your own which updates the prop `currentId`.

```js
const [currentId, setCurrentId] = useState(0);
const next = () => {
    setCurrentId(currentId + 1)
}

return <Stories 
    currentId={currentId}
    onStoryStart={id => setCurrentId(id)}
/>
```
