### ISSUE TITLE
Redirection on See more

### ISSUE THREAD

**Issue by saurabhsinha1991** [mohitk05/react-insta-stories#59]
Currently, seeMore can load a new component. Is there a way to redirect to a new url on click of seemore?

**Comment by swayam2k15** [comment]
> Currently, seeMore can load a new component. Is there a way to redirect to a new url on click of seemore?

I am also facing similar issue while redirection. @mohitk05  can you please help us with it?
Thanks in advance.  :)

**Comment by iMerica** [comment]
One way to solve it using a thunk:

```jsx
const seeMoreFactory = (url) => {
  return ({close}) => {
    close()
    window.open(url, '_blank')
    return null
  }
}

const stories = data.map(story => ({
  url: story.image,
  type: 'image',
  seeMore: seeMoreFactory(story.link)
}))

const App = () => (
  <Stories
    stories={stories}
  />
)
```

**Comment by nastari** [comment]
AWESOME Imerica
