### ISSUE TITLE
Can't perform a React state update on an unmounted component

### ISSUE THREAD

**Issue by eversonverissimo** [mohitk05/react-insta-stories#85]
Most of the time, when I try to load a story with only one video, the video doesn't play, goes to the next user and logs the error message in the console:

`Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in a useEffect cleanup function.
    in Unknown (created by b)
    in b (created by ListStoriesModal)
    in div (created by Unstable_TrapFocus)
    in Unstable_TrapFocus (created by ForwardRef(Modal))
    in div (created by ForwardRef(Modal))
    in ForwardRef(Portal) (created by ForwardRef(Modal))
    in ForwardRef(Modal) (created by ListStoriesModal)
    in div (created by ListStoriesModal)
    in ListStoriesModal (created by AppComponent)`

**Comment by mohitk05** [comment]
Hey, can you provide a CodeSandbox demo or the actual code if it's open? I see there's either some issue with the way you are trying to implement `ListStoriesModal` or with the video. Alternatively, you can try updating the package to the latest `2.1.1` version and try again first, if it still does not work then please add a demo link here.

**Comment by mohitk05** [comment]
Hey, I think this should be resolved with #130, you can update to v2.2.1.
