### ISSUE TITLE
List of stories

### ISSUE THREAD

**Issue by SL-CodeBlaster** [mohitk05/react-insta-stories#87]
i have list of different stories and when click one of story how can i activate clicked story as a active story?

**Comment by mohitk05** [comment]
@SL-CodeBlaster did not get your use case exactly. Can you please elaborate or provide some demo code?

**Comment by SL-CodeBlaster** [comment]
> @SL-CodeBlaster did not get your use case exactly. Can you please elaborate or provide some demo code?

now it's working thank you
