### ISSUE TITLE
ReferenceError: document is not defined integrating with Nextjs

### ISSUE THREAD

**Issue by toelapiut** [mohitk05/react-insta-stories#94]
ReferenceError: document is not defined error shows when integrating with nextjs. Literally, you don't need to add any props rather than the required one. Please fix this

**Comment by frxzn** [comment]
Load the component from client side

**Comment by frxzn** [comment]
https://nextjs.org/docs/advanced-features/dynamic-import#with-no-ssr

**Comment by chwzr** [comment]
here you go

```js 
import dynamic from 'next/dynamic'
const Stories = dynamic(
  () => import('react-insta-stories'),
  { ssr: false }
)
```

**Comment by mohitk05** [comment]
@toelapiut I hope @chwzr 's solution works. Essentially, you can defer the loading to client-side. The package depends on window objects at places, I'll see if I can remove those deps. Closing this for now.
