### ISSUE TITLE
Videos doesn't work on iOS devices

### ISSUE THREAD

**Issue by oachoor** [mohitk05/react-insta-stories#96]
After updating to the major release 2.1.x, the videos doesn't load anymore, It keeps on showing the loader.
I had to revert to 2.0.4 for now until further investigation.

**Comment by solkpolk** [comment]
Images does not load on Safari when using 2.0.4

**Comment by moninm** [comment]
Any news about that ? We are facing the same issue

**Comment by moninm** [comment]
[https://github.com/mohitk05/react-insta-stories/pull/103](url)

**Comment by oachoor** [comment]
Issue gone after installing https://www.npmjs.com/package/react-insta-stories/v/2.1.3

**Comment by robson-danilo** [comment]
Na versão atual 2.6.2 voltou a fazer ao mesmo problema, o video no ios fica lá carregando e nunca é exibido.
